### ISSUE TITLE
What is a CRC file?

### ISSUE THREAD

**Issue by dkfellows** [hpcflow/matflow-new#267]
You have a template component `sample_texture_from_CRC_file` and a parameter `CRC_file_path`. **What is a CRC file in this context?**

I can't find anything even vaguely likely with an online search, but that might be because there are several other very large concepts with those initials (notably Cyclic Redundancy Check from programming/computer engineering, and the CRC Materials Science and Engineering Handbook in materials science) so searching is particularly difficult.

**Comment by mikesmic** [comment]
It’s a data file for EBSD maps collected using Oxford instruments detectors (all UoMs ebsd systems are from OI). These files come as a pair with a .cpr file, cpr is metadata and crc is binary data.

Other formats you might encounter are .ctf which is a plain text/table data file and .h5oina which is a hdf5 based format OI defined about 5 years ago, I don’t think it is used in matflow yet though.

On 27 Nov 2024, at 09:41, Donal Fellows ***@***.***> wrote:

﻿

You have a template component sample_texture_from_CRC_file and a parameter CRC_file_path. What is a CRC file in this context?

I can't find anything even vaguely likely with an online search, but that might be because there are several other very large concepts with those initials (notably Cyclic Redundancy Check from programming/computer engineering, and the CRC Materials Science and Engineering Handbook in materials science) so searching is particularly difficult.

**Comment by dkfellows** [comment]
Thank you. That ("Oxford Instruments") lets me find https://mtex-toolbox.github.io/EBSD.export_crc.html and enough info to say that it's probably some sort of crystallographic data. Shame there isn't an expansion anywhere for what "CRC" stands for in this case.

**Comment by aplowman** [comment]
> Thank you. That ("Oxford Instruments") lets me find https://mtex-toolbox.github.io/EBSD.export_crc.html and enough info to say that it's probably some sort of crystallographic data. Shame there isn't an expansion anywhere for what "CRC" stands for in this case.

Yeah, EBSD experiments are used to study crystallographic structure. According to ChatGPT ("What do the EBSD formats CRC and CPR stand for?"), they are: 

- CRC: Channel Reconstruction File
- CPR: Channel Project File

, which sound plausible. CTF is Channel Text File.

**Comment by dkfellows** [comment]
Thank you both; this has made #265 better.
